# Generated by Django 3.1.7 on 2021-03-04 04:23

import crud.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', editable=False, max_length=350, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=crud.models.upload_location)),
                ('email', models.EmailField(blank=True, max_length=64, null=True, unique=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, choices=[('STANDARD', 'base employee'), ('MANAGER', 'manager'), ('SR_MANAGER', 'senior manager')], max_length=25, null=True)),
                ('detail', models.TextField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
